CREATE TABLE finance_category (
    finance_category_id BIGINT NOT NULL AUTO_INCREMENT,
    primary_category VARCHAR(255) NOT NULL,
    sub_category VARCHAR(255) NOT NULL,
    PRIMARY KEY (finance_category_id),
    UNIQUE KEY uq_finance_category (primary_category, sub_category)
);

INSERT INTO finance_category (primary_category, sub_category) VALUES
('IT Management Systems', 'IT Service Management'),
('IT Management Systems', 'Collaboration & Productivity'),
('IT Management Systems', 'Cloud Platforms & Integration'),
('IT Management Systems', 'Workflow Automation & Low-Code'),
('IT Management Systems', 'Application & Platform Management'),
('IT Management Systems', 'Infrastructure & Operations'),
('IT Management Systems', 'Other IT Management'),
('Accounting & Financial Systems', 'ERP'),
('Accounting & Financial Systems', 'Financial Management'),
('Accounting & Financial Systems', 'Financial Reporting & Consolidation'),
('Accounting & Financial Systems', 'Financial Data & Analytics'),
('Accounting & Financial Systems', 'Travel & Expenses'),
('Accounting & Financial Systems', 'Tax & Statutory Compliance'),
('Accounting & Financial Systems', 'Other Accounting & Financial'),
('Design & Drafting Software', 'Design Authoring Systems'),
('Design & Drafting Software', 'Surveying & Field Set-out'),
('Design & Drafting Software', 'Reality Capture & Point Clouds'),
('Design & Drafting Software', 'Model Coordination & Clash Detection'),
('Design & Drafting Software', 'GIS & Spatial Modelling'),
('Design & Drafting Software', 'BIM Information & Model Data Management'),
('Design & Drafting Software', 'Other Design & Drafting'),
('Estimation & Bidding Systems', 'Estimating Management'),
('Estimation & Bidding Systems', 'Quantity Take-off & Measurement'),
('Estimation & Bidding Systems', 'Cost Planning & Pricing'),
('Estimation & Bidding Systems', 'Tender & Bid Management'),
('Estimation & Bidding Systems', 'Estimate Review & Benchmarking'),
('Estimation & Bidding Systems', 'Subcontractor Pricing'),
('Estimation & Bidding Systems', 'Other Estimating & Bidding'),
('Document Management Systems', 'Document Control & EDMS'),
('Document Management Systems', 'Common Data Environment (CDE)'),
('Document Management Systems', 'PDF Review & Mark-up'),
('Document Management Systems', 'Digital Signatures & Approvals'),
('Document Management Systems', 'Records, Email & Archive Management'),
('Document Management Systems', 'Standards & Technical Content'),
('Document Management Systems', 'Other Document Management'),
('Project Management Systems', 'Productivity & Events'),
('Project Management Systems', 'Controls, Planning & Scheduling'),
('Project Management Systems', 'Forecasting & Performance'),
('Project Management Systems', '4D Sequencing & Staging'),
('Project Management Systems', 'Subcontractor Management'),
('Project Management Systems', 'Resource & Work Management'),
('Project Management Systems', 'Other Project Management'),
('Cybersecurity management systems', 'Identity & Access Management'),
('Cybersecurity management systems', 'Security Operations & Monitoring'),
('Cybersecurity management systems', 'Endpoint, Network & Cloud Security'),
('Cybersecurity management systems', 'Vulnerability & Threat Management'),
('Cybersecurity management systems', 'Security Governance, Risk & Compliance'),
('Cybersecurity management systems', 'Security Awareness & Training'),
('Cybersecurity management systems', 'Other Cybersecurity'),
('Marketing & Advertising Systems', 'Creative Design & Publishing'),
('Marketing & Advertising Systems', 'Video & Multimedia Production'),
('Marketing & Advertising Systems', 'Sales Enablement & Content'),
('Marketing & Advertising Systems', 'Digital Marketing & Campaigns'),
('Marketing & Advertising Systems', 'Brand & Asset Management'),
('Marketing & Advertising Systems', 'Feedback & Market Research'),
('Marketing & Advertising Systems', 'Other Marketing & Advertising'),
('Data & Analytics Systems', 'Business Intelligence & Reporting'),
('Data & Analytics Systems', 'Data Integration & Automation'),
('Data & Analytics Systems', 'Data Governance & Quality'),
('Data & Analytics Systems', 'GIS & Spatial Analytics'),
('Data & Analytics Systems', 'Industry & Market Intelligence'),
('Data & Analytics Systems', 'Operational Analytics'),
('Data & Analytics Systems', 'Other Data & Analytics'),
('Risk, Legal & Compliance Systems', 'Legal Systems'),
('Risk, Legal & Compliance Systems', 'Compliance & Due Diligence'),
('Risk, Legal & Compliance Systems', 'Enterprise & Project Risk Management'),
('Risk, Legal & Compliance Systems', 'Quantitative Risk Analysis'),
('Risk, Legal & Compliance Systems', 'Requirements & Interface Management'),
('Risk, Legal & Compliance Systems', 'Permits & Regulatory Management'),
('Risk, Legal & Compliance Systems', 'Other Risk, Legal & Compliance'),
('Quality Assurance Systems', 'Quality Management'),
('Quality Assurance Systems', 'Inspection & Test Management'),
('Quality Assurance Systems', 'Model Assurance & Compliance'),
('Quality Assurance Systems', 'Commissioning & Handover'),
('Quality Assurance Systems', 'Defects & Snagging'),
('Quality Assurance Systems', 'Audit & Non-Conformance Management'),
('Quality Assurance Systems', 'Other Quality Assurance'),
('HR & Payroll Systems', 'Recruitment Management'),
('HR & Payroll Systems', 'People Management'),
('HR & Payroll Systems', 'Payroll'),
('HR & Payroll Systems', 'Time & Attendance'),
('HR & Payroll Systems', 'Workforce Planning & Mobilisation'),
('HR & Payroll Systems', 'Learning Management (LMS)'),
('HR & Payroll Systems', 'Other HR & Payroll'),
('Supply Chain Management Systems', 'Procurement / Source-to-Contract'),
('Supply Chain Management Systems', 'Vendor & Contractor Management'),
('Supply Chain Management Systems', 'Subcontract Management'),
('Supply Chain Management Systems', 'Material Tracking & Logistics'),
('Supply Chain Management Systems', 'Supply Chain Compliance'),
('Supply Chain Management Systems', 'Supplier Performance'),
('Supply Chain Management Systems', 'Other Supply Chain'),
('Safety & Environmental Impact Assessment Systems', 'Safety Management'),
('Safety & Environmental Impact Assessment Systems', 'Environmental & Sustainability Management'),
('Safety & Environmental Impact Assessment Systems', 'Chemical & Hazchem Management'),
('Safety & Environmental Impact Assessment Systems', 'Incident, Injury & Health Management'),
('Safety & Environmental Impact Assessment Systems', 'Workforce Safety & Compliance'),
('Safety & Environmental Impact Assessment Systems', 'Environmental Monitoring'),
('Safety & Environmental Impact Assessment Systems', 'Other Safety & Environmental'),
('Customer Relationship Management (CRM) Systems', 'CRM Core'),
('Customer Relationship Management (CRM) Systems', 'Stakeholder & Community Engagement'),
('Customer Relationship Management (CRM) Systems', 'Business Development & Pipeline'),
('Customer Relationship Management (CRM) Systems', 'Customer & Client Communications'),
('Customer Relationship Management (CRM) Systems', 'Relationship & Contact Management'),
('Customer Relationship Management (CRM) Systems', 'Customer Insights'),
('Customer Relationship Management (CRM) Systems', 'Other CRM'),
('On-site Communication Systems', 'Field Collaboration & Mobile Forms'),
('On-site Communication Systems', 'Site Logistics & Delivery Coordination'),
('On-site Communication Systems', 'Visitor & Site Access Management'),
('On-site Communication Systems', 'Field Communication & Messaging'),
('On-site Communication Systems', 'Site Progress Capture'),
('On-site Communication Systems', 'Workforce Communications'),
('On-site Communication Systems', 'Other On-site Communication'),
('Equipment Management Systems', 'Plant Management'),
('Equipment Management Systems', 'Fleet & Telematics'),
('Equipment Management Systems', 'Payload & Production Monitoring'),
('Equipment Management Systems', 'Equipment Inspection & Maintenance'),
('Equipment Management Systems', 'Equipment Scheduling & Allocation'),
('Equipment Management Systems', 'Asset Tracking'),
('Equipment Management Systems', 'Other Equipment Management');
