CREATE TABLE finance_view (
    finance_view_id INT NOT NULL AUTO_INCREMENT,
    tenant_id BIGINT NOT NULL,
    source VARCHAR(255) NULL,
    budget VARCHAR(255) NULL,
    software_code VARCHAR(100) NULL,
    erp VARCHAR(100) NULL,
    cost_code VARCHAR(100) NULL,
    location VARCHAR(255) NULL,
    vendor_id INT NULL,
    software_name VARCHAR(255) NULL,
    baseline_budget DECIMAL(15,2) NULL,
    software_spend DECIMAL(15,2) NULL,
    actuals DECIMAL(15,2) NULL,
    remaining DECIMAL(15,2) NULL,
    managed_service_providers DECIMAL(15,2) NULL,
    it_staff_internal_labour DECIMAL(15,2) NULL,
    it_staff_external_labour DECIMAL(15,2) NULL,
    depreciation_amortisation DECIMAL(15,2) NULL,
    cloud_solutions DECIMAL(15,2) NULL,
    consulting_outside_services DECIMAL(15,2) NULL,
    total_tco DECIMAL(15,2) NULL,
    cost_recoveries DECIMAL(15,2) NULL,
    PRIMARY KEY (finance_view_id),
    INDEX idx_finance_view_tenant_id (tenant_id),
    INDEX idx_finance_view_vendor_id (vendor_id)
);
