ALTER TABLE entitlements
    ADD COLUMN software_code VARCHAR(100) NULL,
    ADD COLUMN vendor_id INT NULL,
    ADD COLUMN functional_grouping VARCHAR(255) NULL,
    ADD COLUMN functional_owner VARCHAR(255) NULL,
    ADD COLUMN confidence_level VARCHAR(100) NULL,
    ADD COLUMN manufacturer_name VARCHAR(255) NULL,
    ADD COLUMN system_category VARCHAR(255) NULL,
    ADD COLUMN system_categorization VARCHAR(255) NULL,
    ADD COLUMN business_criticality VARCHAR(100) NULL,
    ADD COLUMN system_strategy VARCHAR(100) NULL,
    ADD COLUMN erp_system VARCHAR(100) NULL,
    ADD COLUMN annual_infrastructure_cost DECIMAL(15,2) NULL,
    ADD COLUMN annual_cost_non_license DECIMAL(15,2) NULL,
    ADD COLUMN annual_license_cost DECIMAL(15,2) NULL,
    ADD COLUMN annual_cost_total DECIMAL(15,2) NULL,
    ADD COLUMN acs_budget DECIMAL(15,2) NULL,
    ADD COLUMN number_of_active_users INT NULL,
    ADD COLUMN number_of_licenses_owned INT NULL,
    ADD COLUMN proposed_function_group_owner VARCHAR(255) NULL,
    ADD COLUMN billing_vendor VARCHAR(255) NULL,
    ADD COLUMN billing_vendor_id INT NULL,
    ADD COLUMN business_function VARCHAR(255) NULL,
    ADD COLUMN number_of_users INT NULL,
    ADD COLUMN budget_owner VARCHAR(255) NULL,
    ADD COLUMN primary_it_group VARCHAR(255) NULL,
    ADD COLUMN primary_it_group_leadership VARCHAR(255) NULL,
    ADD COLUMN contract_duration VARCHAR(100) NULL,
    ADD COLUMN payment_schedule VARCHAR(100) NULL,
    ADD COLUMN currency VARCHAR(10) NULL,
    ADD COLUMN criticality_levels VARCHAR(100) NULL,
    ADD COLUMN description TEXT NULL,
    ADD INDEX idx_entitlements_software_code (software_code),
    ADD INDEX idx_entitlements_vendor_id (vendor_id);
